---
- name: atualizar node
  hosts: all
  become: yes
  tasks:
    - name: Instalar nvm 
      shell: |
        curl https://raw.github.com/creationix/nvm/master/install.sh | bash
      register: nvm_install

    - name: atualizar node
      shell: |
        nvm install 18.20.0 && nvm use 18.20.0 && nvm alias default 18.20.0
        
    - name: Verificar versão node
      shell: node -v
      register: node_version

    - name: Exibir versão do Node.js
      debug:
        msg: "Versão {{ node_version.stdout }}"
