---
- name: atualizar node
  hosts: all
  become: yes
  tasks:
    - name: Verificar se a pasta de logs existe
      stat:
        path: /root/.nvm
      register: pasta_nvm

    - name: Instalar nvm
      shell: |
        curl https://raw.github.com/creationix/nvm/master/install.sh | bash
      when: not pasta_nvm.stat.exists
      
    - name: atualizar node
      command: nvm install 18.20.0 && nvm use 18.20.0 && nvm alias default 18.20.0
        
    - name: Verificar versão node
      shell: node -v
      register: node_version

    - name: Exibir versão do Node.js
      debug:
        msg: "Versão {{ node_version.stdout }}"
