- name: Enviar uma mensagem para o Discord com os nomes dos hosts
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: no
  tasks:
    - name: Recuperar os nomes dos hosts
      set_fact:
        server_names: "{{ groups['all'] | map('extract', hostvars, 'inventory_hostname') | list | unique }}"

    - name: Criar a mensagem formatada com os nomes dos hosts
      set_fact:
        mensagem: |
          Clientes Atualizados - {{ ansible_date_time.iso8601 }}:
          {% for name in server_names %}
          - {{ name }}
          {% endfor %}

    - name: Mostrar mensagem a ser enviada
      debug:
        msg: "{{ mensagem }}"

    - name: Enviar mensagem para o Discord via webhook
      uri:
        url: "https://discord.com/api/webhooks/1283574115793502270/LZYF7ssUK4puSIHbK3iXcAU60gDdBWitgnCyAwILhqMU75VMm1EFsn3jNCKFpznutN9i"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ {'content': mensagem} | to_json }}"
        body_format: json
        return_content: yes
        status_code: [200, 204]
      register: resultado
      ignore_errors: yes 

    - name: Mostrar resultado do envio para o Discord
      debug:
        msg: "{{ resultado }}"
