---
- name: Enviar uma mensagem para o Discord com os nomes dos servidores
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Recuperar nomes dos servidores
      set_fact:
        server_names: "{host}"
        
    - name: Enviar mensagem para o Discord via webhook
      uri:
        url: "https://discord.com/api/webhooks/1283574115793502270/LZYF7ssUK4puSIHbK3iXcAU60gDdBWitgnCyAwILhqMU75VMm1EFsn3jNCKFpznutN9i"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ {'content': mensagem} | to_json }}"
        body_format: json
        return_content: yes
      register: resultado

    - name: Exibir resultado
      debug:
        msg: "{{ resultado }}"
