---
- name: Send a message to the Discord channel
  hosts: localhost
  tasks:
    - name: Send a message to Discord via webhook
      uri:
        url: "https://discord.com/api/webhooks/1283574115793502270/LZYF7ssUK4puSIHbK3iXcAU60gDdBWitgnCyAwILhqMU75VMm1EFsn3jNCKFpznutN9i"
        method: POST
        headers:
          Content-Type: "application/json"
        body: '{"content": "This is a message from Ansible"}'
        body_format: json
