---
- name: Enviar uma mensagem para o Discord com os nomes dos hosts
  hosts: all
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Recuperar os nomes dos hosts
      set_fact:
        server_names: "{{ groups['all'] | map('extract', hostvars, 'inventory_hostname') | list }}"

    - name: Consolidar a mensagem em um único host
      set_fact:
        mensagem: |
          Clientes Atualizados:
          {% for name in server_names %}
          - {{ name }}
          {% endfor %}
      delegate_to: localhost

    - name: Enviar mensagem para o Discord via webhook
      uri:
        url: "https://discord.com/api/webhooks/1283574115793502270/LZYF7ssUK4puSIHbK3iXcAU60gDdBWitgnCyAwILhqMU75VMm1EFsn3jNCKFpznutN9i"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ {'content': mensagem} | to_json }}"
        body_format: json
        return_content: yes
        status_code: [200, 204]
      delegate_to: localhost
      ignore_errors: yes

    - name: Exibir o resultado do envio para verificação
      debug:
        msg: "Resultado do envio: {{ resultado }}"
      delegate_to: localhost
