---
- name: Enviar uma mensagem para o Discord com os nomes dos hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Recuperar os nomes dos hosts
      set_fact:
        server_names: "{{ groups['all'] | map('extract', hostvars, 'inventory_hostname') | list }}"

    - name: Exibir os nomes dos hosts para verificação
      debug:
        msg: "Nomes dos hosts recuperados: {{ server_names }}"

    - name: Criar a mensagem formatada com os nomes dos hosts
      set_fact:
        mensagem: |
          Nomes dos hosts:
          {% for name in server_names %}
          - {{ name }}
          {% endfor %}

    - name: Exibir a mensagem formatada para verificação
      debug:
        msg: "Mensagem formatada a ser enviada: {{ mensagem }}"

    - name: Enviar mensagem para o Discord via webhook
      uri:
        url: "https://discord.com/api/webhooks/1283574115793502270/LZYF7ssUK4puSIHbK3iXcAU60gDdBWitgnCyAwILhqMU75VMm1EFsn3jNCKFpznutN9i"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ {'content': mensagem} | to_json }}"
        body_format: json
        return_content: yes
        status_code: [200, 204]  # Aceitar 200 e 204 como códigos de status válidos
      register: resultado
      ignore_errors: yes  # Ignorar erros para evitar falhas no playbook

    - name: Exibir o resultado do envio para verificação
      debug:
        msg: "Resultado do envio: {{ resultado }}"
