---
- name: Atualizar repositório e verificar interrupções
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes

  tasks:
    - name: Atualizar o repositório
      command: git pull
      args:
        chdir: /var/www/html/iptell/
      register: pull_result

    - name: Verificar se a atualização foi interrompida
      fail:
        msg: "Git pull falhou. Verifique o diretório do repositório."
      when: pull_result.rc != 0
