- name: Checkout do Git
  hosts: all
  become: yes
  tasks:        
    - name: Verificar o estado do repositório Git
      shell: |
         cd /var/www/html/iptell/ && git status && git checkout master
      register: git_status
      changed_when: false
      
    - name: Exibir comando e saída do checkout master
      debug:
        msg:  "{{ git_status.stdout }}"
