---
- name: Executar Git Pull
  hosts: all
  become: yes
  tasks:
    - name: Executar
      shell: |
        cd /var/www/html/iptell && git pull
      register: gitpull_output
    - name: Exibir a saída do git pull
      debug:
        msg: "Saída do git pull: {{ gitpull_output.stdout }}"
