- name: Teste ifconfig
  hosts: all
  become: yes
  tasks:
    - name: Executar ifconfig
      shell: ifconfig
      register: ifconfig_output

    - name: Exibir saída do ifconfig
      debug:
        msg: "{{ ifconfig_output.stdout }}"
