---
- name: Instalar PHP cURL
  hosts: all
  become: yes
  tasks:
    - name: Atualizar cache do apt
      apt:
        update_cache: yes

    - name: Instalar pacote php-curl
      apt:
        name: php-curl
        state: present
