---
- name: Verificar versão do Node.js
  hosts: all
  become: yes

  tasks:
    - name: Executar comando node -v
      shell: node -v
      register: node_version

    - name: Verificar se a versão do Node.js é maior ou igual a 18
      fail:
        msg: "Versão {{ node_version.stdout }}"
      when: node_version.stdout | regex_search('^v?(1[0-7]|[1-9][0-9]*)(\.)') is defined
