---
- name: Instalar PM2 e executar npm run production
  hosts: all
  become: yes
  tasks:
    - name: Executar o comando npm run production
      shell: cd /var/www/html/iptell && npm run production
      register: npm_run_result

    - name: Verificar se o comando de produção foi bem-sucedido
      fail:
        msg: "Falha ao executar o comando 'npm run production'. Erro: {{ npm_run_result.stderr }} Saída: {{ npm_run_result.stdout }}"
      when: npm_run_result.rc != 0
