---
- name: Verificar instalação do php-curl
  hosts: all
  become: yes
  tasks:
    - name: Verificar se o pacote php-curl está instalado
      shell: |
        dpkg -s php-curl
      register: php_curl_status
      ignore_errors: yes

    - name: Imprimir saída do comando dpkg
      debug:
        msg: "{{ php_curl_status.stdout }}"
        
