---
- name: PM2 PROCESSOS
  hosts: all
  become: yes
  tasks:
    - name: Listar processos PM2 antes da remoção
      shell: pm2 ls
      register: pm2_list_before
      changed_when: false

    - name: Remover processos específicos
      shell: pm2 delete {{ item }}
      loop:
        - iptell-api
        - nova-tela-agente
        - novo-backend
      ignore_errors: yes 

    - name: Listar processos PM2 após a remoção
      shell: pm2 ls
      register: pm2_list_after
      changed_when: false

    - name: Exibir lista de processos PM2 antes da remoção
      debug:
        msg: "\n{{ pm2_list_before.stdout }}"

    - name: Exibir lista de processos PM2 após a remoção
      debug:
        msg: "Processos PM2 após a remoção:\n{{ pm2_list_after.stdout }}"
