---
- name: Gerenciar processos PM2
  hosts: all
  become: yes
  tasks:
    - name: Listar processos PM2
      shell: pm2 ls
      register: pm2_list
      changed_when: false

    - name: Remover todos os processos PM2 (exceto Hub e Integração)
      shell: pm2 delete {{ item }}
      loop: "{{ pm2_list.stdout_lines | select('search', '^(?!.*(Hub|Integração)).*') | map('regex_replace', '.*\\s(\\d+)\\s.*', '\\1') | list }}"
      when: "'Hub' not in pm2_list.stdout and 'Integração' not in pm2_list.stdout"
      changed_when: true

    - name: Remover processos específicos (se necessário)
      shell: pm2 delete {{ item }}
      loop: "{{ pm2_list.stdout_lines | select('search', '(Hub|Integração)') | map('regex_replace', '.*\\s(\\d+)\\s.*', '\\1') | list }}"
      when: "'Hub' in pm2_list.stdout or 'Integração' in pm2_list.stdout"
      changed_when: true
