---
- name: Gerenciar processos PM2
  hosts: all
  become: yes
  tasks:
    - name: Listar processos PM2
      command: pm2 ls
      register: pm2_list
      changed_when: false

    - name: Remover todos os processos PM2 (exceto Hub e Integração)
      command: pm2 delete {{ item }}
      loop: "{{ pm2_list.stdout_lines | select('search', '^(?!.*(Hub|Integração)).*') | map('regex_replace', '.*\\s(\\d+)\\s.*', '\\1') | list }}"
      when: pm2_list.stdout | regex_search('(Hub|Integração)') == false
      changed_when: true 
    - name: Remover processos específicos (se necessário)
      command: pm2 delete {{ item }}
      loop: "{{ pm2_list.stdout_lines | select('search', '(Hub|Integração)') | map('regex_replace', '.*\\s(\\d+)\\s.*', '\\1') | list }}"
      when: pm2_list.stdout | regex_search('(Hub|Integração)') == true
      changed_when: true  
