- name: Ping all hosts
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Execute ping command
      shell: pwd
      register: pwd_output

    - name: Show ping results
      debug:
        msg: "{{ pwd_output.stdout }}"
