---
- name: Executar comandos em um shell
  hosts: all
  gather_facts: no

  tasks:
    - name: Verificar a variável shell1
      debug:
        msg: "A variável shell1 é: {{ shell1 }}"

    - name: Executar comando fornecido
      shell: "{{ shell1 }}"
      register: result

    - name: Exibir resultado do comando
      debug:
        var: result.stdout
