---
- name: Executar comandos em um shell
  hosts: all
  gather_facts: no

  tasks:
    - name: Exibir variáveis extras
      debug:
        msg: "{{ extra_vars }}"  # Exibindo as variáveis passadas

    - name: Executar comando fornecido
      shell: "{{ comando }}"  # Aqui você deve usar a variável correta
      register: result

    - name: Exibir resultado do comando
      debug:
        var: result.stdout  # Mostrando a saída do comando
