---
- name: teste com JIRA
  hosts: all
  tasks:
    - name: mostrar variáveis
      shell: "{{ shell1 }}"
      register: shell11

    - name: Exibir resultado do comando
      debug:
        msg: "{{ shell11 }}"
