---
- name: Executar comandos em um shell
  hosts: all
  gather_facts: no

  tasks:
    - name: Verificar se extra_vars foi passado
      debug:
        var: extra_vars

    - name: Exibir variáveis extras
      debug:
        msg: "{{ extra_vars }}"  # Exibindo as variáveis passadas

    - name: Exibir resultado do comando
      debug:
        var: result.stdout  # Mostrando a saída do comando
