---
- name: Executar comandos em um shell
  hosts: all
  gather_facts: no

  tasks:
    - name: Executar comando fornecido
      shell: "{{ comando }}"
      register: result

    - name: Exibir resultado do comando
      debug:
        var: result.stdout
