---
- name: Gerenciar PM2
  hosts: all
  become: yes
  tasks:
    - name: Reiniciar todos os processos PM2
      shell: pm2 restart all
      register: pm2_logs
      ignore_errors: yes

    - name: Imprimir logs do reinício
      debug:
        msg: "{{ pm2_logs.stdout }}"

    - name: Sincronizar lista de processos PM2
      shell: pm2 save
      when: pm2_logs.stdout is search('Current process list is not synchronized')
      ignore_errors: yes
