---
- name: Verificar conectividade dos hosts e exibir informações
  hosts: all
  become: yes
  tasks:
    - name: Verificar conectividade dos hosts
      ping:

    - name: Mostrar informações dos fatos do Ansible
      debug:
        msg: "{{ ansible_facts }}"
