---
- name: Verificar versão do Node.js
  hosts: all
  become: yes

  tasks:
    - name: Executar comando node -v
      shell: node -v
      register: node_version

    - name: Mostrar a versão do Node.js
      debug:
        msg: "A versão do Node.js é: {{ node_version.stdout }}"

    - name: Extrair partes da versão do Node.js
      set_fact:
        node_version_parts:
          major: "{{ node_version.stdout | regex_replace('^v', '') | regex_replace('\\..*', '') | int }}"
          minor: "{{ node_version.stdout | regex_replace('^v', '') | regex_replace('^[0-9]+\\.', '') | regex_replace('\\..*', '') | int }}"
          patch: "{{ node_version.stdout | regex_replace('^v', '') | regex_replace('^[0-9]+\\.[0-9]+\\.', '') | int }}"

    - name: Verificar se a versão do Node.js é maior ou igual a 18.10.0
      fail:
        msg: "A versão do Node.js é inferior a 18.10.0. A versão atual é: {{ node_version.stdout }}"
      when: >
        (node_version_parts.major < 18) or
        (node_version_parts.major == 18 and node_version_parts.minor < 10) or
        (node_version_parts.major == 18 and node_version_parts.minor == 10 and node_version_parts.patch < 0)
