---
- name: VERIFICAR VERSÃO NODE
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes

  tasks:
    - name: Executar comando node -v
      shell: node -v
      register: node_version

    - name: SE A VERSÃO FOR MENOR QUE 18, RETORNAR FALHA
      fail:
        msg: "{{ node_version.stdout }}. É necessário atualizar para a versão 18 ou superior."
      when: node_version.stdout | regex_search('^v(18|[2-9][0-9])\\.\\d+\\.\\d+$') == false
    
