---
- name: Verificar versão do Node.js
  hosts: all
  become: yes

  tasks:
    - name: Executar comando node -v
      shell: node -v
      register: node_version

    - name: Verificar se a versão do Node.js é maior ou igual a 18
      fail:
        msg: "A versão do Node.js é inferior a 18. A versão atual é: {{ node_version.stdout }}"
      when: (node_version.stdout | regex_replace('^v', '') | regex_replace('\\..*', '') | int) < 18
