---
- name: Verificar versão do Node.js
  hosts: all
  become: yes

  tasks:
    - name: Executar comando node -v
      shell: node -v
      register: node_version

    - name: Mostrar a versão do Node.js
      debug:
        msg: "v.{{ node_version.stdout }}"

    - name: Verificar se a versão do Node.js é maior ou igual a 18.10.0
      fail:
        msg: "A versão do Node.js é inferior a 18.10.0. A versão atual é: {{ node_version.stdout }}"
      when: >
        {{ node_version.stdout | regex_replace('^v', '') | 
        split('.') | 
        map('int') | 
        list | 
        (item[0] < 18) or 
        (item[0] == 18 and item[1] < 10) or 
        (item[0] == 18 and item[1] == 10 and item[2] < 0) }}
