---
- name: Verificar node
  hosts: all
  become: yes

  tasks:
    - name: Executar comando node -v
      shell: node -v
      register: node_version

    - name: verificar se a versão é maior que 18.
      fail:
        msg: "{{ node_version.stdout }}. É necessário atualizar para a versão 18 ou superior."
      when: node_version.stdout | regex_search('^v(18|[2-9][0-9])\\.\\d+\\.\\d+$') == false
    
