---
- name: Verificar versão do Node.js
  hosts: all
  become: yes

  tasks:
    - name: Executar comando node -v
      shell: node -v
      register: node_version

    - name: Extrair partes da versão do Node.js
      set_fact:
        version_parts: "{{ node_version.stdout | regex_replace('^v', '') | split('.') | map('int') | list }}"
    
    - name: Verificar se a versão do Node.js é maior ou igual a 18.10.0
      fail:
        msg: "A versão do Node.js é {{ node_version.stdout }}. É necessário atualizar para a versão 18.10.0 ou superior."
      when: >
        version_parts[0] < 18 or
        (version_parts[0] == 18 and version_parts[1] < 10) or
        (version_parts[0] == 18 and version_parts[1] == 10 and version_parts[2] < 0)

    - name: Exibir versão do Node.js
      debug:
        msg: "A versão do Node.js é {{ node_version.stdout }}. Está atualizada."
      when: >
        version_parts[0] > 18 or
        (version_parts[0] == 18 and version_parts[1] > 10) or
        (version_parts[0] == 18 and version_parts[1] == 10 and version_parts[2] >= 0)
