---
- name: Verificar versão node.
  hosts: all
  become: yes

  tasks:
    - name: Executar comando node -v
      shell: node -v
      register: node_version
      msg: "v.{{ node_version.stdout }}"
    - name: Verificar se a versão do Node.js é maior ou igual a 18
      fail:
        msg: "v.{{ node_version.stdout }}"
      when: node_version.stdout | regex_search('^v?(18|[2-9][0-9])\.') == false
