---
- name: Verificar versão do Node.js
  hosts: all
  become: yes

  tasks:
    - name: Executar comando node -v
      shell: node -v
      register: node_version

    - name: Mostrar a versão do Node.js
      debug:
        msg: "A versão do Node.js é: {{ node_version.stdout }}"

    - name: Extrair partes da versão do Node.js
      set_fact:
        node_version_parts: "{{ node_version.stdout | regex_replace('^v', '') | split('.') | map('int') | list }}"

    - name: Verificar se a versão do Node.js é maior ou igual a 18.10.0
      fail:
        msg: "A versão do Node.js é inferior a 18.10.0. A versão atual é: {{ node_version.stdout }}"
      when: >
        (node_version_parts[0] < 18) or
        (node_version_parts[0] == 18 and node_version_parts[1] < 10) or
        (node_version_parts[0] == 18 and node_version_parts[1] == 10 and node_version_parts[2] < 0)
